### PR TITLE
Feature/inheritance

### PR DESCRIPTION
**Pull request by rPraml**
Hi, I've implemented a feature to support @Formula in combination with @ManyToOne.

I need this extension to "inherit" bean references. I've provided a test case that demonstrates some of my use cases.

cheers
Roland

### CODE REVIEW

**Comment by 0xbaadf00d** [comment]
Seems not working on PostgreSQL

```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec <<< FAILURE!
testInheritance(com.avaje.tests.family.TestInheritance)  Time elapsed: 0.025 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<M[aria]> but was:<M[ichael]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.avaje.tests.family.TestInheritance.testInheritance(TestInheritance.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:115)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:102)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
```

**Comment by rPraml** [comment]
it seems that postgres returns the entries in a different order.
The executed query is
````sql
select ... from grand_parent_person t0 

left join (select i1.parent_identifier, count(*) as child_count, sum(i1.age) as child_age 
    from parent_person i1 group by i1.parent_identifier) as f1 
      on f1.parent_identifier = t0.identifier --cardinality: 1

left join parent_person t1 on t1.parent_identifier = t0.identifier --cardinality: n

left join (select i2.parent_identifier, count(*) as child_count, sum(i2.age) as child_age 
    from child_person i2 group by i2.parent_identifier) as f2 
      on f2.parent_identifier = t1.identifier --cardinality: 1

left join grand_parent_person j1 on j1.identifier = t1.parent_identifier --cardinality: 1
left join e_basic t2 on t2.id = coalesce(t1.some_bean_id, j1.some_bean_id) --cardinality: 1
left join e_basic t3 on t3.id = coalesce(t0.some_bean_id,1) --cardinality: 1 

where t0.identifier = ? and (t3.id in (? )  or t3.id is null )  
order by t0.identifier; --bind(1, 1)
```
This query returns the entries in a different order (t1.identifier = 3,2,1)

@rbygrave 
I think if I can change the order by-clause to
```sql
order by t0.identifier, t1.identifier
```
the test will pass. I think this issue is not really related to my patch. Is there a way to enforce the order in a OneToMany relation? (e.g. `@OneToMany(orderBy="identifier")`)

**Comment by rbygrave** [comment]
> Is there a way to enforce the order in a OneToMany relation? (e.g.
@OneToMany(orderBy="identifier"))

Yes, @OrderBy ...

@OrderBy("id")
@OneToMany(...)
List<Foo> foos;


In the past I've been wondering about having a @DefaultOrderBy that you can
put on an entity bean type such that it would apply to any query for that
type that doesn't have an explicitly order by ... and any *ToMany join to
that type.

The thinking there is that generally we don't want arbitrary ordering of
results in OLTP (except for perhaps findEach) and a lot of times there is a
natural ordering expected (by inserted timestamp or by id or alphabetical
non null "name" or "description" property).

Anyway, I haven't done that yet but the idea keeps popping back.

**Comment by rPraml** [comment]
Thanks, Build is passing now. A @DefaultOrderBy would make sense in most of my use cases.

**Pull request merged**
