### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
This pull request change two things :

- Add `.editorconfig` file to force code formatting regardless of developers settings
- Reformat all files to be compliant with the `.editorconfig` file (including 2-spaces indentation)

```
# editorconfig.org

root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true
spaces_around_operators = true
```

### CODE REVIEW

**Comment by rbygrave** [comment]
1,265 files changed.  This is not going to be merged.

**Comment by 0xbaadf00d** [comment]
As you can see on "Files" tab, all changes are about missing space, code indentation, javadoc misformatted, and unused imports removed.

**Comment by rbygrave** [comment]
There are too many files to view the diff.  I understand you probably only made whitespace changes etc but I can't merge it on faith.  I myself never merge anything that large so ... sorry but it's too big.

**Comment by 0xbaadf00d** [comment]
I understand, Is it possible to add `.editorconfig` and reformat all Java files by yourself ?

**Comment by rbygrave** [comment]
I've added the .editorconfig, I'll look to reformat hopefully soon etc. May as well close this then I'd say.

Cheers, Rob.

**Pull request closed without merging**
