### PR TITLE
Replace "for" with "foreach"

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
This pull request replace all basic for loops with foreach loops.
The code is now more simple to read and don't need any more to use extra variables to iterate.

### CODE REVIEW

**Comment by rbygrave** [comment]
The enhanced for loop creates an iterator and extra op codes relative to the "traditional" for i based loop. I micro-benchmarked the "traditional" for loop a while ago as much faster (sure that was some time ago).  On the same vain for i looping over arrays is faster than Lists (and GIT really hops into optimising that) which is why you see "meta data" converted from Lists into arrays internally.

I won't merge this one in until we know foreach can get the same bytecode as for i.

**Comment by rPraml** [comment]
Hello Thibault, Hello Rob,
I made some benchmarks

Iterating over 1000 Integers gives me a test case throughput on a 2.4 GHz CPU:
- **For Loop:** 
145287,696 ops/s => 145_287_696 iterations/s => effective ~16 CPU-Cycles
- **For Each Loop:**
135458,414 ops/s  => ~18 CPU-Cycles

Iterating over 1000 int primitives
- **For Loop:** 
195431,785 ops/s => ~12 CPU-Cycles
- **For Each Loop:**
274157,359 ops/s => ~9 CPU-Cycles (here foreach is much faster than for i)

I am a little bit surprised now, becasue I expected also that _foreach_ is much slower than _for i_, but it seems that the JIT does a very good job now (or my benchmark is wrong)

Rob, I already know a lot of the ebean code and you always take a look at performance :)

But if we really loose only a few CPU Cycles with _foreach_ I would prefer readability over performance.
(if you send a TCP/IP packet to the SQL-server, the performance gain through optimized loop is < 0.00...1% I think)

you can find the benchmarks here: https://github.com/FOCONIS/jmh-playground/
(see the two source files how to run)

**Comment by rbygrave** [comment]
The benchmark looks right to me.

My environment

# JMH 1.15 (released 39 days ago)
# VM version: JDK 1.8.0_102, VM 25.102-b14
# VM invoker: /usr/lib/jvm/jdk1.8.0_102/jre/bin/java
# VM options: -server
# Warmup: 5 iterations, 5 s each
# Measurement: 5 iterations, 5 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Throughput, ops/time


My runs:


Benchmark                                      Mode  Cnt       Score
Error  Units
LoopBenchmark.testBasicForLoop                thrpt    5  258906.882 ±
8240.437  ops/s
LoopBenchmark.testForEach                     thrpt    5  200254.021 ±
6859.844  ops/s
LoopBenchmark.testForEachLambda               thrpt    5  229063.503 ±
23899.393  ops/s
LoopBenchmark.testForLoopWithCachedFinalSize  thrpt    5  243340.105 ±
12480.421  ops/s
LoopBenchmark.testForLoopWithCachedSize       thrpt    5  244890.942 ±
2787.416  ops/s
LoopBenchmark.testWhileIerator                thrpt    5  217094.240 ±
4127.924  ops/s


Benchmark                                      Mode  Cnt       Score
Error  Units
LoopBenchmark.testBasicForLoop                thrpt    5  258942.082 ±
4414.152  ops/s
LoopBenchmark.testForEach                     thrpt    5  202602.586 ±
2785.079  ops/s
LoopBenchmark.testForEachLambda               thrpt    5  232207.959 ±
3689.224  ops/s
LoopBenchmark.testForLoopWithCachedFinalSize  thrpt    5  243121.637 ±
12238.148  ops/s
LoopBenchmark.testForLoopWithCachedSize       thrpt    5  243966.785 ±
15520.398  ops/s
LoopBenchmark.testWhileIerator                thrpt    5  216503.291 ±
6275.039  ops/s



Benchmark                                               Mode  Cnt
Score       Error  Units
LoopPrimitiveBenchmark.testBasicForLoop                thrpt    5
350322.046 ± 13439.162  ops/s
LoopPrimitiveBenchmark.testForEach                     thrpt    5
434423.660 ±  2059.164  ops/s
LoopPrimitiveBenchmark.testForEachLambda               thrpt    5
434274.111 ± 21919.898  ops/s
LoopPrimitiveBenchmark.testForLoopWithCachedFinalSize  thrpt    5
289753.700 ± 13729.717  ops/s
LoopPrimitiveBenchmark.testForLoopWithCachedSize       thrpt    5
295117.069 ± 11463.390  ops/s



Benchmark                                               Mode  Cnt
Score      Error  Units
LoopPrimitiveBenchmark.testBasicForLoop                thrpt    5
356266.637 ± 8260.311  ops/s
LoopPrimitiveBenchmark.testForEach                     thrpt    5
435302.666 ± 6495.241  ops/s
LoopPrimitiveBenchmark.testForEachLambda               thrpt    5
443583.727 ± 8545.905  ops/s
LoopPrimitiveBenchmark.testForLoopWithCachedFinalSize  thrpt    5
295243.918 ± 4182.388  ops/s
LoopPrimitiveBenchmark.testForLoopWithCachedSize       thrpt    5
298308.239 ± 2434.113  ops/s



The primitive arrays are not collections so no iterator required there -
the foreach on primitives is impressive.

My runs for LoopBenchmark testBasicForLoop vs testForEach show a more
significant difference that what your runs produced.

LoopBenchmark.testBasicForLoop                thrpt    5  *258906*.882 ±
8240.437  ops/s
LoopBenchmark.testForEach                     thrpt    5  *200254*.021 ±
6859.844  ops/s


I think a common case in the Ebean code base would be a loop over arrays of
Object ... and for that case I suspect the foreach could be optimised by
the JIT much like the primitive arrays.  I'll look to create a benchmark
for that.

**Comment by dastultz** [comment]
On Mon, Nov 7, 2016 at 7:32 PM, Roland Praml <notifications@github.com>
wrote:

> Hello Thibault, Hello Rob,
> I made some benchmarks
>
> Iterating over 1000 Integers gives me a test case throughput on a 2.4 GHz
> CPU:
>
>    - *For Loop:* 145287,696 ops/s => 145_287_696 iterations/s =>
>    effective ~16 CPU-Cycles
>    - *For Each Loop:* 135458,414 ops/s => ~18 CPU-Cycles
>
> So often it seems when I set out to write a foreach loop I find I have to
exit the loop early, like searching for example. I've gotten in the habit
of writing my loops as for/Iterator:

boolean found = false;
for (Iterator<T> iter = ...; iter.hasNext() && found;){
...found = ...
}

I'd be interested in seeing the benchmark with an Iterator as above, I
guess without the "found" part.

/Daryl

**Comment by rbygrave** [comment]
Benchmark                              Mode  Cnt       Score       Error
Units
LoopObjArrBenchmark.testBasicForLoop  thrpt    5  314133.628 ±  3639.838
ops/s
LoopObjArrBenchmark.testForEach       thrpt    5  355333.845 ± 21998.221
ops/s


Benchmark                              Mode  Cnt       Score       Error
Units
LoopObjArrBenchmark.testBasicForLoop  thrpt    5  313681.669 ±  2966.489
ops/s
LoopObjArrBenchmark.testForEach       thrpt    5  365241.804 ± 13639.514
ops/s


So yes, foreach over an array of objects gets some meaningful optimisation
improvement over the basic for i loop (just like the array of primitives).

My gut feeling is that this is the most common case in the code base of
Ebean internals ... and this suggests this merge request should go in.

Nice. I'll review the merge request again.

**Comment by rbygrave** [comment]
The whitespace standard for this project is 2 spaces (not 4). I can take differences with a limited number of files but this changes 131 files so for me I can't accept that.

**Comment by 0xbaadf00d** [comment]
I'm sorry, default for IntelliJ is 4 space. I will reformat files with 2 spaces whitespace today. I will try to submit a new Pull Request for the issue #859  with all files converted with 2 spaces whitespace and force compatible IDE (IntelliJ, Visual Code, ...) to use 2-space rather than 4.

**Comment by 0xbaadf00d** [comment]
Ok, just re-push with 2-spaces whitespace.

**Pull request merged**
