### PR TITLE
FIX for IAE "key can't be empty"  in System.getProperty() 

### PR DESCRIPTION
**Pull request by rPraml**
*How to reproduce*
use a property placeholder like `${}` somewhere in the config file

### CODE REVIEW

**Comment by rPraml** [comment]
@rbygrave changed file should be reformatted, as it uses tabs instead of spaces

**Comment by rbygrave** [comment]
Why do we think `${}` is valid ?  Should it not through an IAE ?

**Comment by rPraml** [comment]
I use it for collation setting. e.g. `lcase(${})` which will be translated to an `order by lcase(property)` statement.
See: https://github.com/ebean-orm/ebean/blob/master/src/main/java/io/ebean/OrderBy.java#L336
(maybe the `${}` placeholder was not the best choice here)

**Comment by rbygrave** [comment]
I'm confused.  OrderBy uses StringHelper but not PropertyEval so I don't see how the suggested change impacts OrderBy ?

**Comment by rPraml** [comment]
I have one config file (spring application.properties) where all the config parameters are set. (ebean.*, spring.*, de.foconis.*)
I initialize the ServerConfig with config.loadFromProperties(applicationProperties)
So, if there is any property containing a ${} (in my case something like `de.foconis.customOrderByCollation=lcase(${})`) , PropertiesLoader.eval fails.
I would expect that PropertiesLoader.eval leaves the string untouched, if the property could not be resolved and no default value exists.

**Comment by rbygrave** [comment]
We need a test case for this.

**Comment by rbygrave** [comment]
Oh, in this case we are loading properties into ServerConfig that are not expected to be used by ServerConfig ... but instead used by the application - **all** the properties are going into ServerConfig regardless.

I see.

> maybe the ${} placeholder was not the best choice here

Right, because in the application properties sense `${}` doesn't make sense.

**Comment by rPraml** [comment]
I have provided a test case. The main issue is, that properties that are not ebean related will prohibit ebean from start.
Note that you often have no control what strings are in the property files.

**Comment by rbygrave** [comment]
Ok, I've pushed the change with a test.  We can close this PR (fixed in master).

**Pull request closed without merging**
