### PR TITLE
Add NamingConvention Support for JoinColumn (OneToMany, ManyToOne)

### PR DESCRIPTION
**Pull request by lvffilho**

### CODE REVIEW

**Comment by rbygrave** [comment]
What is the use case (example) where the existing functionality is not working?  Can you give an example of the issue this fixes (before and after).

Thanks

**Comment by rbygrave** [comment]
What's going on here?

**Comment by lvffilho** [comment]
If a have a class with JoinColumn define, and configure a CamelCaseNamingConvention. Ebean do not call convert method and name still "area_type_id". The correct would be areaTypeId using my namingConvention. The same problem occur whem my @JoinColumn dont have a "name" property the framework only concat property + _ + fk and dont call naming convention.

```
@Entity
public class Area extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @ManyToOne
    @JoinColumn(name = "area_type_id")
    @NotNull
    private AreaType areaType;
```

**Comment by rbygrave** [comment]
Fixed as https://github.com/ebean-orm/ebean/issues/906

I'll close this one.

**Pull request closed without merging**
